# Configure file for Rolling Scoreboard plugin

# =========================================
# |            Basic Configure            |
# =========================================

# The language that Rolling Scoreboard plugin will use to display information
# Examples: "en_us", "zh_cn"
language: zh_cn

# The filter that Rolling Scoreboard plugin will use
# none, the plugin will not use any filter to filter
# blacklist, the plugin will use server's blacklist to filter
# independent_blacklist, the plugin will use a independent blacklist to filter
# whitelist, the plugin will use server's whitelist to filter
# independent_whitelist, the plugin will use a independent whitelist to filter
# general_whitelist, the plugin will use WhitePaper's general whitelist plugin to filter
# auto_filter, the plugin will use a build-in auto filter to filter
filter: none

# Set default scoreboard interval
# This setting is used if the scoreboard is not individually assigned a dwell time
# Unit: seconds
# Examples: "10", "0.1"
default_scoreboard_interval: 10

# Add "rsb." prefix in scoreboards' names to prevent scoreboard confusion
# true, enable this setting
# false, disable this setting
prevent_scoreboard_confusion: true