# Configure file for Rolling Scoreboard plugin

# =========================================
# |            Basic Configure            |
# =========================================

# The language that Rolling Scoreboard plugin will use to display information
# Examples: "en_us", "zh_cn"
language: zh_cn

# The filter that Rolling Scoreboard plugin will use
# none, the plugin will not use any filter to filter
# blacklist, the plugin will use server's blacklist to filter
# independent_blacklist, the plugin will use a independent blacklist to filter
# whitelist, the plugin will use server's whitelist to filter
# independent_whitelist, the plugin will use a independent whitelist to filter
# general_whitelist, the plugin will use WhitePaper's general whitelist plugin to filter
# auto_filter, the plugin will use a build-in auto filter to filter
filter: none

# Set default scoreboard interval
# This setting is used if the scoreboard is not individually assigned a dwell time
# Unit: seconds
# Examples: "10", "0.1"
default_scoreboard_interval: 10

# Add "rsb." prefix in scoreboards' names to prevent scoreboard confusion
# true, enable this setting
# false, disable this setting
prevent_scoreboard_confusion: true

# Automatic Start & Stop
# When there is someone in the server, it will start to scroll the list automatically, otherwise it will stop
# Note: to judge whether there is a real player on the server, you need to use a filter. If there is no filter, BOT may
#       be judged as a real player
# true, enable this setting
# false, disable this setting
auto_start&stop: true

# Delete the echo of scoreboard instruction recorded in log file
# Only tested on the vanilla server
clean_log: false

# ============================================
# |           Permission Configure           |
# ============================================
# Set player permission in MCDR's permission.yml file
# Available levels (top to down):
# 0, - owner
# 1, - admin
# 2, - helper
# 3, - user
# 4, - guest

# Set global command permissions
# true, enable this setting
# false, disable this setting
global_permission: false
global_permission_level: 2

# Command to show the control panel of the plugin
pannel_permission_level: 2

# Help command
help_permission_level: 2

# List all loaded scoreboards
list_permission_level: 2

# Reload all scoreboards
reload_permission_level: 2

# Unload all scoreboards
unload_permission_level: 2

# Start to roll scoreboards
start_permission_level: 2

# Stop rolling scoreboards
stop_permission_level: 2

# Add new scoreboard
add_permission_level: 2

# Delete scoreboard
del_permission_level: 2

# =========================================
# |           Advance Configure           |
# =========================================
# enable console debug output
# true, enable this setting
# false, disable this setting
debug_mode: false

# =========================================
# |           Missing Configure           |
# =========================================

# Options below were missing and set by RollingScoreboard plugin with default value
# Remember to check and update the them as soon as possible